### ISSUE TITLE
 Unable to send. googleapi: Error 403: Insufficient Permission, insufficientPermissions

### ISSUE THREAD

**Issue by hyp530** [uttamgandhi24/send-gmail#1]
" Unable to send. googleapi: Error 403: Insufficient Permission, insufficient Permissions"

Hi, I got the above result. Do you know how to fix the permission problem?

Thank you.

**Comment by hyp530** [comment]
And I tried to reset by revoking the authorization. But it gets worse. This time it shows:

Get https://www.googleapis.com/gmail/v1/users/me/labels?alt=json: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant",
  "error_description" : "Token has been revoked."
}

Do you know how to fix it? Thank you.

**Comment by uttamgandhi24** [comment]
1. Ensure you have changed the permission to gmail.MailGoogleComScope
2. Remove the credentials/gmail-go-quickstart.json file and re-run the program

I hope, that helps

**Comment by hyp530** [comment]
Thank you very much. I removed the auto created .credentials folder and it works fine.

**Comment by uttamgandhi24** [comment]
You are welcome
